In [1]:
#Import packages
import numpy as np
import matplotlib.pyplot as plt
import random as rd
import scipy.linalg as la
from numpy.linalg import matrix_power as mpow

In [2]:
#1 a) Scalar variables. Make the following varialbes.
a=10
b=2.5*(10**23)  #Can use b = 2.5e23
c=2+3j #i^2=-1, use 1j for i and 3j for 3i
d=np.exp((1j*2*np.pi)/3)
print(a)
print(b)
print(c)
print(d)

10
2.5e+23
(2+3j)
(-0.4999999999999998+0.8660254037844387j)


In [3]:
#b) Vector variables: Make the following variables, as numpy arrays
u=np.array([3.14,15,9,26])
#print(u)

v=np.array([[2.71],[8],[28],[182]])
#print(v)

w=np.array([5.0])
for i in range(50):
    #w=np.insert(w,i+1,5.0-0.2*(i+1))   Same thing
    w=np.append(w,5.0-0.2*(i+1))
#print(w)
# Can also use: w = np.arange(5,-5.2,-0.2)
# w = np.linspace(5,-5,51) # alternative to arange

m=np.array(np.logspace(0,1,num=100))
#print(m)
#np.log10(1/m) # to see the exponents

In [4]:
#c) Matrix variables: Make the following variables.
A=np.full((9,9),2)
#print(A)

B=np.diag([1,2,3,4,5,4,3,2,1])
#print(B)

C=np.array([],dtype=np.int64)
for i in range (100):
    C=np.append(C,i+1)
C=np.reshape(C,(10,10))
C=C.T
#print(C)

D=np.array([[13,-1,5],[-22,10,87]])
#print(D)

E=6*np.random.random_sample((5,3))-3
E=np.round(E)
print(E)

[[-1.  1. -0.]
 [ 3.  2. -1.]
 [ 1. -2.  3.]
 [ 0.  2.  2.]
 [-3. -1. -2.]]


In [5]:
#d) Scalar expressions: Using the variables created in (a), calculate x and y.
x=1/(1+np.exp(-(a-15)/6))
print(x)

y=(np.log(np.real((c+d)*(c-d))*np.sin(a*np.pi/3)))/(c*np.conj(c))
print(y)

0.3029407160345927
(0.10463356619618336+0j)


In [6]:
#e) Vector expressions: Using the variables created in (b), evaluate the expressions below, elementwise.
x=(1/(np.sqrt(2*np.pi*(2.5**2))))*np.exp((-v**2)/(2*2.5**2))
print(x)

y=np.sqrt(u.T**2+v**2)
print(y)

z=np.log10(1/m)
#print(z)

[[8.86767747e-02]
 [9.53635281e-04]
 [9.20492284e-29]
 [0.00000000e+00]]
[[  4.14773432  15.24283766   9.39915422  26.14085117]
 [  8.59416081  17.          12.04159458  27.20294102]
 [ 28.17551419  31.76476035  29.41088234  38.20994635]
 [182.0270848  182.61708573 182.2223916  183.84776311]]


In [11]:
#f) Matrix expressions: Using variables in (b) and (c), evaluate below using matrix operations
X=np.dot(u,v)*mpow(A,2)
#print(X)

Y=np.dot(v,[u])
#print(Y)

Z=la.det(C)*((A@B).T)
#print(Z)

In [12]:
#g) Common functions and indexing
print(np.sum(C, axis=0))    #column-wise sum of C
print(np.mean(C,axis=1))    #row-wise mean of C

#Display second column of D
col2=D[:,1]
print(col2)

#Display first row of D
row1=D[0,:]
print(row1)

#Replace top row of D with [1 1 1]
g=np.array([[1,1,1],D[1,:]])
print(g)
D=g

#Extract submatrix of C that contains row 2 through 9 and columns 2 through 9
#print(C[1:9,1:9])

#Make vector k = (1 2 ... 20), then make every other value in it negative so k = (1 -2 3 -4 ... 19 -20)
k=np.array(range(1,21))
k[1::2]=-k[1::2]
print(k)

#Make r a 1x5 vector using np.random.random_sample.
#Find elements that are less than 0.5 and set to 0.
#Use array indexing on left-hand-side of assignment
r=np.random.random_sample((1,5))
r=np.select([r<0.5],[0],r) #r[r<0.5]=0 simple
print(r) #This isn't intended, but works. Look at intended solution

[ 55 155 255 355 455 555 655 755 855 955]
[46. 47. 48. 49. 50. 51. 52. 53. 54. 55.]
[ 1 10]
[1 1 1]
[[  1   1   1]
 [-22  10  87]]
[  1  -2   3  -4   5  -6   7  -8   9 -10  11 -12  13 -14  15 -16  17 -18
  19 -20]
[[0.        0.7790852 0.        0.        0.       ]]


In [14]:
#2. Convergence of infinite series. Look at two series that converge to finite value when summed.
# (a) geometric series
r=0.99
k=np.arange(0,1001)
S = 1/(1-r) # infinite sum
ak = r**k # sequence
Sk = np.cumsum(ak) # partial sums
print(Sk)

[ 1.          1.99        2.9701     ... 99.99563927 99.99568288
 99.99572605]
